name: TestAndBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.12

    - name: Build
      run: go build cmd/redump/main.go

    - name: Test
      run: go test -coverprofile coverage.out -covermode atomic -v ./...

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
        infile: coverage.out
        outfile: coverage.lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
